### ISSUE TITLE
Failed to set audio session category

### ISSUE THREAD

**Issue by heshesh2010** [yosemiteyss/flutter_volume_controller#73]
I got this error when change the audio category on real ios device to force video mute and unmute when I pressed on ringer button 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(1009, Failed to set audio session category, The operation couldn’t be completed. (OSStatus error 561017449.), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
<asynchronous suspension>
#2      FlutterVolumeController.setIOSAudioSessionCategory (package:flutter_volume_controller/src/flutter_volume_controller.dart:223:7)
<asynchronous suspension>

**Comment by yosemiteyss** [comment]
https://developer.apple.com/documentation/coreaudiotypes/avaudiosessionerrorinsufficientpriority
You may need some extra handling for this scenario.

**Comment by heshesh2010** [comment]
> https://developer.apple.com/documentation/coreaudiotypes/avaudiosessionerrorinsufficientpriority You may need some extra handling for this scenario.

do u have any idea how to handle this case ? i'm switching from 

  FlutterVolumeController.setIOSAudioSessionCategory(
        category: AudioSessionCategory.playback,
      );

and

   FlutterVolumeController.setIOSAudioSessionCategory(
        category: AudioSessionCategory.ambient,
      );

when user switch ringer mode from on and off
